### ISSUE TITLE
Change Royalties [Optional]

### ISSUE THREAD

**Issue by butavpaul** [ElvenTools/elven-nft-minter-sc#10]
It would be great to change the royalties, if it's possible on Elrond chain and it's not encoded on the SC at deploy.
But also make a limitation, to avoid very high changes after the launch.
If it's set to 20% at deploy, you can change it only 1-10% after that.

**Comment by juliancwirko** [comment]
Yes, I thought about it, and I wonder if this should be possible when there are NFTs already sold. Maybe only before the first one is sold. Because otherwise, different tokens from the same collection would have other royalties, and I wonder if randomly generated 'art' should have various royalties. In my opinion, the collection should be concise across all tokens regarding uris, royalties, etc. Only the price is, in my opinion, something which can be changed because it is a strong marketing tool, and prices will be different across secondary markets anyway. I think the price is slightly different from royalties in that context. The prices depend on the market, and royalties should be defined upfront for the whole collection.

But as always, this is just my opinion. There should be an option to change the royalties if there are no tokens sold. Similar to changing the base CIDs. So for sure, let's keep this thread open. I will implement that. But I am not sure yet about changing them after some of the tokens are sold.

**Comment by tannerhallman** [comment]
Although I can appreciate some safeguards or suggestions, I think it should be up to the collection owner to make any changes they deem necessary to properly manage their collection. So unless there's an Elrond restriction or problem with changing royalties during the mint, it would appear as a subjective restriction and not an objective one.

Royalties are a very important part of managing a collection of NFTs. My vote (not that it really matters) would be to consider this functionality.

**Comment by juliancwirko** [comment]
I need to rethink that. I see your point, and you are correct that the owner should decide. In the end, it is their smart contract, and they will be responsible for trust, etc. Good point, thanks for that!
